== `RunConfiguration.getProjectDir()` returns null outside katalon project

=== The blocker problem

See the source of link:{TreeURL}/katalon/Scripts/misc/listTestObjects/Script1746006212468.groovy[Test Cases/misc/listTestObjects]. I called `com.kms.katalon.core.configuration.RunConfiguration.getProjectDir()` to find the path of "katalon" project.

[source,groovy]
----
include::../katalon/Scripts/misc/listTestObjects/Script1746006212468.groovy[lines=10..12]
----

When I ran this code in Katalon Studio, it printed the path of the `katalon` project folder successfully.

[source,text]
----
include::assets/testcase_output.txt[lines=3..5]
----

Yes, `RunConfiguration.getProjectDir()` is the established way of obtaining the file path of a Katalon project's folder. It works properly in Katalon Runtime Engine as well.

However, `RunConfiguration.getProjectDir()` does not work outside Katalon Studio. I wrote a JUnit test:

- link:{TreeURL}/lib/listTestObjects/Script1746006212468.groovy[`lib/src/test/groovy/com/kms/katalon/core/configuration/RunConfigurationFailingTest.groovy`]

[source,text]
----
include::../lib/src/test/groovy/com/kms/katalon/core/configuration/RunConfigurationFailingTest.groovy[]
----

When I ran this JUnit test, it failed.

[source,text]
----
$ ./gradlew :lib:test --tests com.kms.katalon.core.configuration.RunConfigurationFailingTest

> Task :lib:test FAILED

RunConfigurationFailingTest > test_getProjectDir() FAILED
    org.opentest4j.AssertionFailedError at RunConfigurationFailingTest.groovy:11
----

[source,text]
----
org.opentest4j.AssertionFailedError: projectDir=null ==> expected: <true> but was: <false>
	at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at app//org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at app//org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at app//org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:214)
	at java.base@17.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.11/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at app//groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at app//org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrap.invoke(StaticMetaMethodSite.java:131)
	at app//org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:100)
	at app//org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at app//org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at app//org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:240)
	at app//com.kms.katalon.core.configuration.RunConfigurationFailingTest.test_getProjectDir(RunConfigurationFailingTest.groovy:11)
    ...
----

The **`RunConfiguration.getProjectDir()` returned null in the `lib` subproject**!

This is a serious blocker for me. If my codes in the `lib` subproject can not get the path of `katalon` project folder, my codes can not get the path of `Object Repository` folder and the Test Objects at all. I am at a loss what to do in the `lib` subproject.

=== The resolution

I invented a magic spell: `io.github.kazurayam.ks.configuration.RunConfigurationConfigurator`. Later I will explain what it does. See how it works as in the following JUnit test:

- link:{TreeURL}/lib/listTestObjects/Script1746006212468.groovy[`lib/src/test/groovy/com/kms/katalon/core/configuration/RunConfigurationPassingTest.groovy`]

[source,text]
----
include::../lib/src/test/groovy/com/kms/katalon/core/configuration/RunConfigurationPassingTest.groovy[]
----

When I ran this JUnit test, it passed. This means, a call to `RunConfiguration.getProjectDir()` in a JUnit test in the `lib` subproject successfully returned the path of the `katalon` subproject. The issue has been resolved!

=== Description

I developed 2 tricky Groovy classes.

==== KatalonProjectDirectoryResolver

- link:{TreeURL}/lib/src/main/groovy/io/github/kazurayam/ks/configuration/KatalonProjectDirectoryResolver.groovy[`io.github.kazurayam.ks.configuration.KatalonProjectDirectoryResolver`]

[source,groovy]
----
include::../lib/src/main/groovy/io/github/kazurayam/ks/configuration/KatalonProjectDirectoryResolver.groovy[]
----

The static `KatalonProjectDirectoryResolver.getProjectDir()` method will return a Path object, which is the `katalon` subproject's root folder.

When the method is called inside Katalon Studio runtime, the method simply returns a non-null value returned by `RunConfiguration.getProjectDir()`. When the `RunConfiguration.getProjectDir()` returned null, the method presumes that it was invoked in the sibling `lib` subproject, and returns a path `../katalon` relative the the `lib` subproject.

As you can perceive, the `KatalonProjectDirectoryResolver` is designed for limited use local to the `lib` subproject of this `Katalon-IDEA-Combination` project.


==== RunConfigurationConfigurator






